/*
 * View.java
 *
 * Created on 30 de Outubro de 2009, 23:53
 */

package lsi111.view;

import lsi111.Controller;
import javax.swing.JOptionPane;

/**
 *
 * @author  Brian /José Julio
 */
public class View extends javax.swing.JFrame {

    private Controller controller;
    /** Creates new form View */
    public View(Controller controller) {
        this.controller = controller;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        editor = new org.jdesktop.swingx.JXEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivos = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemQuit = new javax.swing.JMenuItem();
        jMenuLexico = new javax.swing.JMenu();
        JMenuSintatico = new javax.swing.JMenu();
        jMenuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilador ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSplitPane1.setDividerLocation(400);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        editor.setDoubleBuffered(true);
        jScrollPane1.setViewportView(editor);

        jSplitPane1.setLeftComponent(jScrollPane1);

        output.setColumns(20);
        output.setEditable(false);
        output.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        output.setLineWrap(true);
        output.setRows(5);
        output.setWrapStyleWord(true);
        jScrollPane2.setViewportView(output);

        jSplitPane1.setRightComponent(jScrollPane2);

        jMenuArquivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user-home.png"))); // NOI18N
        jMenuArquivos.setText("Arquivos");

        jMenuItemOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/document-open.png"))); // NOI18N
        jMenuItemOpen.setText("Abrir...");
        jMenuItemOpen.setToolTipText("Abrir um projeto ...");
        jMenuItemOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuItemOpenMouseReleased(evt);
            }
        });
        jMenuArquivos.add(jMenuItemOpen);

        jMenuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/document-save-as.png"))); // NOI18N
        jMenuItemSave.setText("Salvar como...");
        jMenuItemSave.setToolTipText("Salve seu projeto...");
        jMenuItemSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuItemSaveMouseReleased(evt);
            }
        });
        jMenuArquivos.add(jMenuItemSave);

        jMenuItemQuit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/system-log-out.png"))); // NOI18N
        jMenuItemQuit.setText("Sair");
        jMenuItemQuit.setToolTipText("Sair do Aplicativo...");
        jMenuItemQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitActionPerformed(evt);
            }
        });
        jMenuArquivos.add(jMenuItemQuit);

        jMenuBar1.add(jMenuArquivos);

        jMenuLexico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/applications-development.png"))); // NOI18N
        jMenuLexico.setText("Léxico");
        jMenuLexico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLexicoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuLexico);

        JMenuSintatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/applications-system.png"))); // NOI18N
        JMenuSintatico.setText("Sintático");
        JMenuSintatico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMenuSintaticoMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMenuSintatico);

        jMenuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/go-home.png"))); // NOI18N
        jMenuSobre.setText("Sobre");
        jMenuSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSobreMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenuItemQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitActionPerformed
    this.dispose();
}//GEN-LAST:event_jMenuItemQuitActionPerformed

private void jMenuSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSobreMouseClicked
String sobre ="UFSC / INE / CTC\n" +
                "Graduaçao em Sistemas de Informação\n" +
                "INE5622 - Introdução a Compiladores\n" +
                "Profa. Jerusa Marchi \n\n" +
                "Alunos: Gabriel Gonçalves Nunes Mazetto\n" +
                "\tLuis Artur Ribeiro de Lima\n";
        JOptionPane.showMessageDialog(null, sobre, "Sobre", JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_jMenuSobreMouseClicked

private void jMenuItemOpenMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemOpenMouseReleased
    controller.open_file();
}//GEN-LAST:event_jMenuItemOpenMouseReleased

private void jMenuItemSaveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemSaveMouseReleased
    controller.save_as();
}//GEN-LAST:event_jMenuItemSaveMouseReleased

private void JMenuSintaticoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMenuSintaticoMouseClicked
    controller.syntaticAnalisys(editor.getText());
}//GEN-LAST:event_JMenuSintaticoMouseClicked

private void jMenuLexicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLexicoMouseClicked
    controller.lexicalAnalisys(editor.getText());
}//GEN-LAST:event_jMenuLexicoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuSintatico;
    public org.jdesktop.swingx.JXEditorPane editor;
    private javax.swing.JMenu jMenuArquivos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemQuit;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenu jMenuLexico;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    public javax.swing.JTextArea output;
    // End of variables declaration//GEN-END:variables

}
